version: "3.9"
name: leet-fleet
services:
  # By default Compose sets up a single network for your app. Each container for a service joins the
  # default network and is both reachable by other containers on that network, and discoverable by
  # them at a hostname identical to the container name.
  # client:
  #   image: "client:latest"
  #   depends_on:
  #     - "wish_I_knew"