version: "3.9"
name: leet-fleet
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
      - ./data:/data
  # client:
  #   image: "client:latest"
  #   depends_on:
  #     - "wish_I_knew"
